#!/bin/sh
# Detour UDP broadcast packages to a specific network interface using iptables.
# Useful for playing LAN games over VPN which discover servers via UDP broadcast.

USAGE="Usage: detourbrd { IFACE MTU X IP NETMASK | reset }"

[ -x "$(command -v ipcalc)" ] || { echo "ipcalc not found!" ; exit 1; }
[ "$1" != reset ] && [ $# -lt 5 ] && { echo "$USAGE" ; exit 1; }

iptables -t nat -F || exit 1
[ "$1" == "reset" ] && { echo "Reset UDP broadcast detour" ; exit 0; }

IFACE=$1
SUBNET_SOURCE=$4
NETMASK=$5

SUBNET_BROADCAST=$(ipcalc ${SUBNET_SOURCE}/${NETMASK} | awk '{ if($1 == "Broadcast:") { print $2 } }')
[ -z "$SUBNET_BROADCAST" ] && { echo "Broadcast address not found!" ; exit 1; }

echo "Broadcast address: $SUBNET_BROADCAST"

iptables -t nat -A OUTPUT -p udp --destination 255.255.255.255 -j DNAT --to-destination $SUBNET_BROADCAST && \
iptables -t nat -A POSTROUTING -p udp --destination $SUBNET_BROADCAST -j SNAT --to-source $SUBNET_SOURCE && \
iptables -t nat -L

exit 0
